pipeline {
    agent any

    environment {
        IMAGE_NAME = 'momer99/mlops-a1'
        DOCKER_TAG = "${env.BUILD_NUMBER}"
    }

    stages {
        stage('Clone Repository') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    bat "docker build -t %IMAGE_NAME%:%DOCKER_TAG% -f Docker/Dockerfile ."
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                script {
                    withCredentials([string(credentialsId: 'DOCKER_PASSWORD', variable: 'DOCKER_PASSWORD')]) {
                        bat "docker login -u momer99 -p %DOCKER_PASSWORD%"
                        bat "docker push %IMAGE_NAME%:%DOCKER_TAG%"
                    }
                }
            }
        }
    }

    post {
        success {
            mail to: 'ma359192002@gmail.com',
            subject: "Deployment Successful",
            body: "The latest version (%DOCKER_TAG%) has been successfully deployed.",
        }
        failure {
            mail to: 'ma359192002@gmail.com',
            subject: "Deployment Failed",
            body: "The deployment of version (%DOCKER_TAG%) failed. Check Jenkins logs for details.",
        }
    }
}
