name: Create and Merge PR from Dev to Test

on:
  workflow_run:
    workflows: ["Code Quality Check"]
    types:
      - completed

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: test
          branch: dev
          title: "Auto PR: Merge Dev into Test"
          body: "This PR merges the latest changes from `dev` into `test`."
          labels: "automated-pr"
