name: Merge Dev to Test

on:
  workflow_run:
    workflows: ["Code Quality Check"]
    types:
      - completed

permissions:
  contents: write  # ✅ Allows pushing changes

jobs:
  merge:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "momer99"
          git config user.email "muhamad01aamir@gmail.com"

      - name: Merge Dev into Test
        run: |
          git fetch origin dev test
          git checkout test
          git pull origin test
          git merge -X theirs origin/dev -m "Merging dev into test, preferring dev changes"
          git push origin test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # ✅ GitHub's default token with write permissions
