name: Create and Merge PR from Dev to Test

on:
  workflow_run:
    workflows: ["Code Quality Check"]
    types:
      - completed

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: test
          branch: dev
          title: "Auto PR: Merge Dev into Test"
          body: "This PR merges the latest changes from `dev` into `test`."
          labels: "automated-pr"

  auto-merge:
    needs: create-pr
    runs-on: ubuntu-latest
    if: ${{ needs.create-pr.result == 'success' && needs.create-pr.outputs.pull-request-number != '' }}
    steps:
      - name: Enable Auto-Merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ needs.create-pr.outputs.pull-request-number }}
          merge-method: squash
