name: Merge Test to master

on:
  workflow_run:
    workflows: ["Code Quality Check"]
    types:
      - completed

jobs:
  merge:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "momer99"
          git config user.email "muhamad01aamir@gmail.com"

      - name: Merge Test into master
        run: |
          git fetch origin master
          git checkout master
          git pull origin master  # Ensure master is up to date
          git merge --no-ff origin/test -m "Auto-merging test into master"
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.AUTOMERGE }}
