name: Feature Testing

on:
  workflow_run:
    workflows: ["Merge Dev to Test"]  # This triggers when "Merge Dev to Test" workflow is completed
    types:
      - completed  # Trigger only when the workflow is completed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: test
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Set up virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate  # Activate the virtual environment

      - name: Install dependencies
        run: |
          source venv/bin/activate  # Ensure we're using the virtual environment
          pip install --upgrade pip  # Upgrade pip to ensure compatibility
          pip install -r src/requirements.txt  # Install dependencies from the requirements file

      - name: Freeze installed packages
        run: |
          source venv/bin/activate  # Ensure we're using the virtual environment
          pip freeze > src/requirements.txt  # Generate a new requirements.txt with only used dependencies

      - name: Run tests
        run: |
          source venv/bin/activate  # Ensure we're using the virtual environment
          pytest src/test_app.py  # Run your tests
