name: Merge Test to Master

on:
  workflow_run:
    workflows: ["Feature Testing"]
    types:
      - completed

jobs:
  merge:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "momer99"
          git config user.email "muhamad01aamir@gmail.com"

      - name: Merge Test into Master
        run: |
          gh pr merge $(gh pr list --base master --head test --json number --jq '.[0].number') --squash --admin
        env:
          GITHUB_TOKEN: ${{ secrets.AUTOMERGE }}
